export const SET_OUTPUT = 'SET_OUTPUT';
export const UPDATE_OUTPUT = 'UPDATE_OUTPUT';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const SET_OPERATOR = 'SET_OPERATOR';
export const TOGGLE_NEGATIVITY = 'TOGGLE_NEGATIVITY';
export const APPEND_TO_INPUT = 'APPEND_TO_INPUT';
export const INPUT_REMOVE_LAST_CHAR = 'INPUT_REMOVE_LAST_CHAR';
export const RESET_FORM = 'RESET_FORM';
